import fs from "fs";
import path from "path";
import url from "url";

import {
  Networked3dWebExperienceServer,
  Networked3dWebExperienceServerConfig,
} from "@mml-io/3d-web-experience-server";
import type { CharacterDescription } from "@mml-io/3d-web-user-networking";
import express from "express";
import enableWs from "express-ws";

import { BasicUserAuthenticator } from "./BasicUserAuthenticator";

const dirname = url.fileURLToPath(new URL(".", import.meta.url));

const PORT = parsePort(process.env.PORT, 8080);
const NODE_ENV = process.env.NODE_ENV ?? "development";

type Logger = {
  info: (message: string, meta?: Record<string, unknown>) => void;
  warn: (message: string, meta?: Record<string, unknown>) => void;
  error: (message: string, meta?: Record<string, unknown>) => void;
};

function parsePort(value: string | undefined, fallback: number) {
  if (!value) {
    return fallback;
  }
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) {
    throw new Error(`Invalid PORT value: ${value}`);
  }
  return parsed;
}

function createLogger(service: string): Logger {
  const log = (level: "info" | "warn" | "error", message: string, meta?: Record<string, unknown>) =>
    console[level](JSON.stringify({ level, service, message, meta }));
  return {
    info: (message, meta) => log("info", message, meta),
    warn: (message, meta) => log("warn", message, meta),
    error: (message, meta) => log("error", message, meta),
  };
}

const logger = createLogger("multi-user-3d-web-experience");

// Specify the avatar to use here:
const characterDescription: CharacterDescription = {
  // Option 1 (Default) - Use a GLB file directly
  meshFileUrl: "/assets/models/bot.glb", // This is just an address of a GLB file
  // Option 2 - Use an MML Character from a URL
  // mmlCharacterUrl: "https://...",
  // Option 3 - Use an MML Character from a string
  // mmlCharacterString: `
  // <m-character src="/assets/models/mml_body_male.glb">
  //   <m-model src="/assets/models/mml_head_hispanic_male.glb"></m-model>
  //   <m-model src="/assets/models/mml_hair_black.glb"></m-model>
  //   <m-model src="/assets/models/mml_torso_hoodie.glb"></m-model>
  //   <m-model src="/assets/models/mml_legs_grey_pants.glb"></m-model>
  //   <m-model src="/assets/models/mml_shoes_retro_white.glb"></m-model>
  // </m-character>
  // `,
};

const userAuthenticator = new BasicUserAuthenticator(characterDescription, {
  /*
   This option allows sessions that are reconnecting from a previous run of the server to connect even if the present a
   session token that was not generated by this run of the server.

   This is useful for development, but in deployed usage, it is recommended to set this to false.
  */
  devAllowUnrecognizedSessions: true,
});

const webClientBuildDir = path.join(dirname, "../../client/build/");
const indexContent = fs.readFileSync(path.join(webClientBuildDir, "index.html"), "utf8");
const mmlDocumentsDirectoryRoot = path.resolve(dirname, "../mml-documents");
const mmlDocumentsWatchPath = "**/*.html";

const { app } = enableWs(express());
app.enable("trust proxy");
app.disable("x-powered-by");

const networked3dWebExperienceServer = new Networked3dWebExperienceServer({
  networkPath: "/network",
  userAuthenticator,
  mmlServing: {
    documentsWatchPath: mmlDocumentsWatchPath,
    documentsDirectoryRoot: mmlDocumentsDirectoryRoot,
    documentsUrl: "/mml-documents/",
  },
  webClientServing: {
    indexUrl: "/",
    indexContent,
    clientBuildDir: webClientBuildDir,
    clientUrl: "/web-client/",
    clientWatchWebsocketPath:
      process.env.NODE_ENV !== "production" ? "/web-client-build" : undefined,
  },
  enableChat: true,
  assetServing: {
    assetsDir: path.resolve(dirname, "../../../assets/"),
    assetsUrl: "/assets/",
  },
  connectionLimits: {
    maxConnections: NODE_ENV === "production" ? 500 : 100,
    maxConnectionsPerIp: NODE_ENV === "production" ? 20 : 10,
  },
  healthChecks: {
    livePath: "/healthz",
    readyPath: "/readyz",
    readinessCheck: () => true,
  },
  logger,
} satisfies Networked3dWebExperienceServerConfig);
networked3dWebExperienceServer.registerExpressRoutes(app);

// Start listening
logger.info("Server starting", { port: PORT });
const server = app.listen(PORT, () => {
  logger.info("Server listening", { port: PORT });
});

const shutdown = (signal: string) => {
  logger.warn("Server shutting down", { signal });
  networked3dWebExperienceServer.dispose();
  server.close(() => {
    logger.info("Server closed", { signal });
    process.exit(0);
  });
};

process.on("SIGINT", () => shutdown("SIGINT"));
process.on("SIGTERM", () => shutdown("SIGTERM"));
